mysite/blog/urls.py
from django.urls import path

from . import views, apis, testViews

app_name = 'blog'

urlpatterns = [
    path('accounts/login/', apis.login, name='login'),
    path('accounts/logout/', apis.logout, name='logout'),
    # path('accounts/register/', apis.register, name='register'),

    path('toLogin/', views.toLogin, name='toLogin'),

    path('', views.toLogin, name=''),
    path('showBlogList', views.showBlogList, name='showBlogList'),
    path('showBlog', views.showBlog, name='showBlog'),
    path('toAddBlog', views.toAddBlog, name='toAddBlog'),
    path('toUpdateBlog', views.toUpdateBlog, name='toUpdateBlog'),
    path('json', views.json, name='json'),

    path('getJSON', apis.getJSON, name='getJSON'),
    path('getAllJSON', apis.getAllJSON, name='getAllJSON'),

    path('getBlogList', apis.getBlogList, name='getBlogList'),
    path('getBlog', apis.getBlog, name='getBlog'),
    path('addBlog', apis.addBlog, name='addBlog'),
    path('deleteBlog', apis.deleteBlog, name='deleteBlog'),
    path('updateBlog', apis.updateBlog, name='updateBlog'),
    path('editBlogColumn', apis.editBlogColumn, name="editBlogColumn"),

    path('getAllAuthor', apis.getAllAuthor, name="getAllAuthor"),
    
    path('loginVerify', apis.loginVerify, name='loginVerify'),

    path('test', testViews.test, name='test'),
    path('extras', testViews.extras, name='extras'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pools', include('pools.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

mysite/pools/urls.py
from django.urls import path

from . import views

app_name = 'pools'

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/blog/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()

    def __unicode__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=50)
    subTitle = models.CharField(max_length=200, blank=True, null=True)
    content = models.TextField()
    counter = models.IntegerField(default=0)
    pubDate = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.title
        

mysite/pools/models.py
from django.db import models

# Create your models here.

mysite/blog/forms.py
#coding=utf-8
from django import forms
from django.contrib.auth.models import User
# from bootstrap_toolkit.widgets import BootstrapDateInput,BootstrapTextInput,BootstrapUneditableInput

class LoginForm(forms.Form):
    username = forms.CharField(
            required = True,
            label=u"用户名",
            error_messages={'required':'请输入用户名'},
            widget=forms.TextInput(
                attrs={
                    'placeholder':u"用户名",
                    }   
                )   
            )   

    password = forms.CharField(
            required=True,
            label=u"密码",
            error_messages={'required':u'请输入密码'},
            widget=forms.PasswordInput(
                attrs={
                    'placeholder':u"密码",
                    }   
                ),  
            )   

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u"用户名和密码为必填项")
        else:
            cleaned_data = super(LoginForm,self).clean()

mysite/blog/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.template import loader
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.db import connection
from blog.models import Blog, Author
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required

# Create your views here.

# return HttpResponseRedirect(reverse('blog:toLogin', args=(question.id,)))
def toLogin(request):
    print('-----toLogin')
    return render(request, "login.html")

@login_required
def showBlog(request, blogId=0):
    if blogId is None or blogId == 0:
        blogId = request.GET.get('blogId', 0)
    print(blogId)
    # blog = Blog.objects.get(id=blogId)
    blog = get_object_or_404(Blog, pk=blogId)
    blog.counter+=1
    blog.save()
    return render(request, "blog.html", {"blog": blog})

@login_required
def showBlogList(request):
    return render(request, "blog_list.html")

@login_required
def toAddBlog(request, message=""):
    authors = Author.objects.all()
    return render(request, "blog_add.html", {"authors": authors, "message": message})

@login_required
def toUpdateBlog(request, blogId=0, message=""):
    if blogId is None or blogId == 0:
        blogId = request.GET['blogId']
    authors = Author.objects.all()
    blog = Blog.objects.get(id=blogId)
    return render(request, "blog_edit.html", {"authors": authors, "blog":blog, "message":message})

def json(request):
    return render_to_response('json.html')

mysite/pools/views.py
from django.http import HttpResponse
from django.shortcuts import render, render_to_response
from blog import apis

def index(request):
    json = apis.getTest()
    print(json)
    return render_to_response("index.html")
    # return HttpResponse("Hello, world. You're at the polls index.")

mysite/blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap-table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
    <style type="text/css">
        *{margin:0;padding:0;list-style-type:none;}
        a,img{border:0;}
        body{font:12px/180% Arial, Helvetica, sans-serif, "微软雅黑";}
        #left{margin: 60px 0px 0px 0px;width:100px; display: inline-block;}
        #left{float:left;}
        #left .navbox ul{width:100px;padding:0;background:url() no-repeat;}
        #left .navbox ul li{margin:10px 0 0 0;}
        #left .navbox ul li a{
            background:#cbcbcb url() no-repeat;color:#174867;padding:10px 15px 10px 15px;width:100px;display:block;text-decoration:none;
            -webkit-transition:all 0.3s ease-out;
            -moz-transition:all 0.3s ease-out;
            -o-transition:all 0.3s ease-out;
            -webkit-box-shadow:2px 2px 4px #888;
            -moz-box-shadow:2px 2px 4px #888;
            -o-box-shadow:2px 2px 4px #888;
        }
        #left .navbox ul li a:hover{background:#ebebeb url() no-repeat;color:#67a5cd;padding:10px 15px 10px 30px;}

        #app {
            position: relative;
            margin:0px auto;
            width:1024px;
            height: 100%;
            background-color: #dddddd;
        }
        #nav {
            position: absolute;
            background-color: #eeeeee;
            width: 100%;
            height: 60px;
        }
        #nav ul {clear: both;}
        #nav ul li a {
            float: left;
            line-height: 60px;
            width: 150px;
            font-size: 30px;
            text-align: center;
            text-decoration:none;
        }
        #nav ul li a:hover {
            color: white;
            background-color: #67a5cd;
        }
        #content {
            position: absolute;
            padding-left: 120px;
            top: 60px;
            width: 100%;
            height: 100%;
            overflow-scrolling: auto;
        }
    </style>
</head>
<body>
    <div id="app">
        <div id="nav">
            <ul>
                <li><a href="#">XHTML</a></li>
                <li><a href="#">XHTML</a></li>
                <li><a href="#">XHTML</a></li>
                <li><a href="#">XHTML</a></li>
                <li><a href="#">XHTML</a></li>
                <li><a href="#">XHTML</a></li>
            </ul>
        </div>
        <div id="left">
            <div class="navbox">
                <ul>
                    <li><a href="#">XHTML</a></li>
                    <li><a href="#">C++</a></li>
                    <li><a href="#">Mootools</a></li>
                    <li><a href="#">HTML5</a></li>
                    <li><a href="#">CSS</a></li>
                    <li><a href="#">jQuery</a></li>
                    <li><a href="#">Ajax</a></li>
                    <li><a href="#">PHP</a></li>
                    <li><a href="#">Perl</a></li>
                </ul>
            </div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <!-- JavaScript 放置在文档最后面可以使页面加载速度更快 -->
    <!-- <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script> -->
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <!-- 可选: 合并了 Bootstrap JavaScript 插件 -->
    <script src="https://apps.bdimg.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="{% static 'custom.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap-table.js' %}"></script>
    <script src="{% static 'bootstrap/locale/bootstrap-table-zh-CN.js' %}"></script>
    <script>

    </script>
</body>
</html>

mysite/blog/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
</head>
<body>
    <button type="button" class="greenBtn" onclick="window.location.href = 'showBlogList';">首页</button>
    <div class="col-md-9">
        <h2>{{blog.title}}</h2>
        <h4>{{blog.subTitle}}</h4>
        作者：{{blog.author.name}}<br/>
        日期：{{blog.pubDate|date:"Y-m-d g:i:s"}}
        <br/>
        <pre>{{blog.content}}</pre>
    </div>
</body>
</html>

mysite/blog/templates/blog_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
</head>
<body>
    <button class="greenBtn" type="button" onclick="window.location.href = 'showBlogList';">首页</button><br/><br/>
    <form id="form" action="{% url 'blog:addBlog' %}" onsubmit="return onSubmitAction()" method="POST">
        {% csrf_token %}
        <input style="min-width: 300px;" id="title" type="text" name="title" placeholder="标题" value="{{title}}" /><br/>
        <input style="min-width: 300px;" id="subTitle" type="text" name="subTitle" placeholder="子标题" value="{{subTitle}}" /><br/>
        <textarea style="min-width: 300px; min-height: 100px;" id="content" type="text" name="content" placeholder="内容">{{content}}</textarea><br/>
        <select id="authorId" name="authorId" form="form" value="{{authorId}}">
            {% for author in authors %}
                <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
        </select><br/><br/>
        <button class="redBtn" type="reset">重置</button>
        <button class="greenBtn" type="submit">提交</button>
    </form>
    <label style="color: red;">{{message}}</label>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery.form.js' %}"></script>
    <script src="{% static 'custom.js' %}"></script>
    <script>
        $("#form").ajaxForm(function(data){
            alert(data.message);
            if(data.status==200){
                window.location.href = '/showBlogList';
            }
        }); 
        function onSubmitAction() {
            var title = document.getElementById("title").value;
            var content = document.getElementById("content").value;
            var authorId = document.getElementById("authorId").value;
            if(isEmpty(title)){
                alert("标题不能为空");
                return false;
            }else if (isEmpty(content)) {
                alert("内容不能为空");
                return false;
            }else if (isEmpty(authorId)) {
                alert("作者不能为空");
                return false;
            }
            return true;
        }
    </script>
</body>
</html>

mysite/blog/templates/blog_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
</head>
<body>
    <button class="greenBtn" type="button" onclick="window.location.href = 'showBlogList';">首页</button><br/><br/>
    <form id="form" action="{% url 'blog:updateBlog' %}" onsubmit="return onSubmitAction()" method="POST">
        {% csrf_token %}
        <input id="blogId" hidden="hidden" type="text" name="blogId" value="{{blog.id}}" />
        <input id="title" type="text" name="title" placeholder="标题" value="{{blog.title}}" /><br/>
        <input id="subTitle" type="text" name="subTitle" placeholder="子标题" value="{{blog.subTitle}}" /><br/>
        <textarea style="min-width: 300px; min-height: 100px;" id="content" type="text" name="content" placeholder="内容">{{blog.content}}</textarea><br/>
        <input id="authorIdInput" hidden="hidden" type="text" value="{{blog.author.id}}" />
        <select id="authorId" name="authorId" form="form" value="{{blog.author.id}}">
            {% for author in authors %}
                <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
        </select><br/><br/>
        <button class="greenBtn" type="submit">提交</button>
    </form>
    <label style="color: red;">{{message}}</label>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery.form.js' %}"></script>
    <script type="text/javascript">
        window.onload = function(){
            var author_select = document.getElementById("authorId");
            var author_select_value = document.getElementById("authorIdInput").value;
            var all_options = author_select.options;
            for (i=0; i<all_options.length; i++){
                if (all_options[i].value == author_select_value)  // 根据option标签的ID来进行判断  测试的代码这里是两个等号
                {
                    all_options[i].selected = true;
                }
            }
        }
        /** 验证文件是否导入成功  */  
        $("#form").ajaxForm(function(data){
            alert(data.message);
            if(data.status==200){
                window.location.href = '/showBlogList';
            }
        }); 
        function onSubmitAction() {
            var title = document.getElementById("title").value;
            var content = document.getElementById("content").value;
            var authorId = document.getElementById("authorId").value;
            if(isEmpty(title)){
                alert("标题不能为空");
                return false;
            }else if (isEmpty(content)) {
                alert("内容不能为空");
                return false;
            }else if (isEmpty(authorId)) {
                alert("作者不能为空");
                return false;
            }
            return true;
        }
    </script>
</body>
</html>

mysite/blog/templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "custom.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "/css/bootstrap-editable.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "/css/bootstrap-table.css" %}">
</head>
<body>
    <div id="app">
        <div align="right"><input type="button" onclick="logout();" value="登出" class="redBtn"></div>
        <div id="toolbar">
            <button style="padding-top: 0px; padding-bottom: 0px;" class="greenBtn" type="button" onclick="toAddAction();">新增</button><br/>    
        </div>
        <table id="table" class="table table-striped table-bordered table-hover table-condensed" style="min-width: 1280px;">
        </table>
    </div>
    <!-- JavaScript 放置在文档最后面可以使页面加载速度更快 -->
    <!-- <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script> -->
    <script src="{% static "jquery.min.js" %}"></script>
    <!-- 可选: 合并了 Bootstrap JavaScript 插件 -->
    <!-- <script src="https://apps.bdimg.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->
    <script src="{% static "custom.js" %}"></script>
    <script src="{% static "/js/bootstrap.js" %}"></script>
    <script src="{% static "/js/bootstrap-editable.js" %}"></script>
    <script src="{% static "/js/bootstrap-table.js" %}"></script>
    <script src="{% static "/js/bootstrap-table-zh-CN.js" %}"></script>
    <script src="{% static "/js/bootstrap-table-editable.js" %}"></script>
    <script>
        // $.fn.bootstrapTable.defaults.mode = 'inline';
        $(function(){
            $('#table').bootstrapTable({
                url: "{% url 'blog:getBlogList' %}",
                method: 'get',
                dataType: "json",
                 //排序方式 
                sortOrder: "asc",
                striped: true,//设置为 true 会有隔行变色效果  
                undefinedText: "-",//当数据为 undefined 时显示的字符  
                pagination: true, //分页  
                paginationPreText: '‹',//指定分页条中上一页按钮的图标或文字,这里是<  
                paginationNextText: '›',//指定分页条中下一页按钮的图标或文字,这里是>  
                // showPaginationSwitch:true,//是否显示 数据条数选择框
                // paginationLoop:true,//设置为 true 启用分页条无限循环的功能。  
                // showToggle: "true",//是否显示 切换试图（table/card）按钮  
                // showColumns: "true",//是否显示 内容列下拉框  
                toolbar: "#toolbar",
                editable: true,
                pageSize: 10,//如果设置了分页，页面数据条数  
                pageList: [10, 20],  //如果设置了分页，设置可供选择的页面数据条数。设置为All 则显示所有记录。  
                // singleSelect: false,//设置True 将禁止多选  
                idField: "id",//指定主键列
                showRefresh: true,
                search: true,
                strictSearch: true,//Enable the strict search.
                clickToSelect: true,
                // data_local: "zh-US",//表格汉化
                sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
                // showExport: true,                    
                // exportDataType: 'all',
                // exportTypes:[ 'csv', 'txt', 'sql', 'doc', 'excel', 'xlsx', 'pdf'],  //导出文件类型
                queryParams: function (params) {//自定义参数，这里的参数是传给后台的，我这是是分页用的
                    return {//这里的params是table提供的
                        offset: params.offset,//从数据库第几条记录开始  
                        limit: params.limit,//找多少条  
                        search: params.search,
                    };  
                },
                // onClickRow: function(row){
                    // window.open("/showBlog?blogId="+row.id);
                // },
                onEditableSave: function(field, row, oldValue, $el) {
                    var post_data = {
                        "blogId": row.id,//获得所在行指定列的值
                        "newValue": row[field],
                        "field": field
                    };
                    $.post("{% url 'blog:editBlogColumn' %}", post_data, function(data, status){
                        if (data["status"]!=200) {
                            alert(data["message"]);
                            row[field] = oldValue;
                            $table = $('#table').bootstrapTable({});
                            $table.bootstrapTable('updateRow', {index: row.rowId, row: row});
                        }
                    });
                },
                columns: [{
                    field: 'id',
                    title: 'ID',
                    visible: true,
                    formatter: function (value, row){
                        return ['<a target="_blank" href="showBlog?blogId='+row.id+'">'+value+'</a>'];
                    }
                }, {
                    field: 'title',
                    title: '标题',
                    width: '35%',
                    editable: {
                        type: "text",                //编辑框的类型。支持text|textarea|select|date|checklist等
                        title: "标题",                //编辑框的标题
                        disabled: false,             //是否禁用编辑
                        emptytext: "空文本",          //空值的默认文本
                        mode: "inline",              //编辑框的模式：支持popup和inline两种模式，默认是popup
                        validate: function (v) {
                            if ($.trim(v) == '') {
                                return '标题不能为空!';
                            }
                        }
                    }
                }, {
                    field: 'subTitle',
                    title: '子标题',
                    width: '25%',
                    editable: {
                        type: 'text',
                        title: '子标题',
                        validate: function (v) {
                            if ($.trim(v) == '') {  
                                return '子标题不能为空!';  
                            }
                        }
                    }
                },  {
                    field: 'counter',
                    title: '访问量',
                    align: 'center'
                }, {
                    field: 'pubDate',
                    title: '日期',
                    align: 'center'
                }, {
                    field: 'author',
                    title: '作者',
                    align: 'center',
                    editable: {
                        type: 'select',
                        title: '作者',
                        pk: 1,
                        // source: [
                            // {value: 1, text: '张三'},
                            // {value: 2, text: '李四'},
                        // ],
                        source: function () {
                            var result = [];
                            //使用ajax同步加载数据
                            $.ajax({
                                url: "{% url 'blog:getAllAuthor' %}",
                                async: false,
                                type: "get",
                                data: {},
                                success: function (data, status) {
                                    $.each(data.result, function (key, value) {
                                        result.push({ value: value.id, text: value.name });
                                    });
                                }
                            });
                            return result;
                        },
                        validate: function (v) {
                            if (!v) return '值不能为空';
                        }
                    }
                }, {
                    title: '操作',
                    align: 'center',
                    formatter: function (value, row){
                        return ['<button class="greenBtn" type="button" onclick="editAction('+row.id+')">修改</button>',
                            '<button class="redBtn" type="button" onclick="deleteAction('+row.id+')">删除</button>',
                        ].join('');
                    }
                }],
                
            });
        });
        function logout() {
            $.get("accounts/logout/", function(data, status){
                alert(data.message);
                if(data.status==200){
                    window.location.href = '/';
                }
            });
        }
        function toAddAction() {
            window.open("/toAddBlog");
        }
        function editAction(blogId) {
            window.open("/toUpdateBlog?blogId="+blogId);
        }
        function deleteAction(blogId) {
            var r=confirm("确认删除?")
            if (r==true){
                $.post("{% url 'blog:deleteBlog' %}", {"blogId":blogId}, function(data, status){
                    alert(data["message"]);
                    if (data["status"]==200) {
                        window.location.reload();
                    }
                });
            }
        }
    </script>
</body>
</html>

mysite/blog/templates/extras.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Extras</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load poll_extras %}
</head>
<body>
    
</body>
</html>

mysite/blog/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
    <style>  
        .align-center{ 
            position: absolute;
            left:50%;
            top:50%;
            margin-left:-100px;
            margin-top:-200px;margin-left:width/2;margin-top:height/2;
        } 
    </style>
</head>
<body>
    <div class="align-center">
        <form id="form" class="form-horizontal" role="form" action="{% url 'blog:login' %}" onsubmit="return onSubmitAction()" id="blogform" method="POST">
            <div class="text-center">
                <h3>登录</h3><br>
                {% csrf_token %}
                <input id="username" class="form-control" name="username" placeholder="用户名" type="text"/><br>
                <input id="password" class="form-control" name="password" placeholder="密码" type="password"/><br><br>
                <button class="redBtn" type="reset">重置</button>
                <button class="greenBtn" type="submit">提交</button>
            </div>
        </form>
    </div>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery.form.js' %}"></script>
    <script src="{% static 'custom.js' %}"></script>
    <script>
        /** 验证文件是否导入成功  */  
        $("#form").ajaxForm(function(data){
            alert(data.message);
            if(data.status==200){
                window.location.href = '/showBlogList';
            }
        }); 
        function onSubmitAction() {
            var username = document.getElementById("username").value;
            var password = document.getElementById("password").value;
            if(isEmpty(username)){
                alert("用户名不能为空");
                return false;
            }else if (isEmpty(password)) {
                alert("密码不能为空");
                return false;
            }
            return true;
        }
    </script>
</body>
</html>

mysite/blog/templates/test.html
{% extends "base.html" %}
{% block title %}测试页面{% endblock %}
 
{% block content %}
    <h1>哈哈哈</h1>
    <h1>哈哈哈</h1>
    <h1>哈哈哈</h1>
{% endblock %}